### Agenda
* Creating a vector and accessing its properties
* Creating a matrix and accessing its properties
* Creating a data frame and accessing its properties
* Creating an array and accessing its properties
* Creating a list and accessing its properties
* Converting matrix to data frame and data frame to matrix
* Creating a list from combination of vector, matrix, and data frames
______________________________________________________________________________________________________________________

### Introduction

#### Basic DataTypes
* Characvter
* Numeric
* Logical
* Integer
* Complex

#### Organized Data Types
* Vector - One type of data .i.e homogenous data type
* Matrix - One type of data but in 2D
* Array - One type of data
* Data frame - Mix type of data, Stores data in tablular format
* List - Hetrogenous data, including vector, matrix, data frames etc.


### Creating vector

In [2]:
cVec <- c("Cricket","Tenis","Rugby")

In [4]:
cVec

[1] "Cricket" "Tenis"   "Rugby"

In [5]:
 cVec <- c(game1="Cricket", game2="Football",        
            game3="Basketball", game4="Rugby")

In [6]:
cVec

game1        game2        game3        game4 
   "Cricket"   "Football" "Basketball"      "Rugby"

In [7]:
nVec <- c(1:10)

In [8]:
nVec

[1]  1  2  3  4  5  6  7  8  9 10

In [9]:
c(TRUE, FALSE, FALSE)

[1]  TRUE FALSE FALSE

* c() is most easy way to create numeric & logical vectors
* runif() - generate uniform distribution of data
* sample()

In [10]:
nvec2 <- runif( n = 5, min=10, max=20)

In [11]:
nvec2

[1] 19.28678 16.65111 16.49353 12.37889 10.31609

In [12]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [13]:
#replace - same data getting repeated
sample(x=letters, size=5, replace = F)

[1] "z" "e" "x" "c" "v"

In [14]:
#get help for anything
? sample

In [18]:
a = 7
is.numeric(7)

[1] TRUE

In [19]:
is.vector(nVec)

[1] TRUE

### Accessing Data

In [20]:
nVec[3]

[1] 3

In [21]:
nVec

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
#Getting vactor of all indices which you want to fetch
nVec[c(2,5,7)]

[1] 2 5 7

## Creating a matrix and accessing its properties

In [1]:
matA <- matrix(1, nrow = 2, ncol = 4)

In [2]:
matA

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 1    1    1    1

In [3]:
#byrow - filling information by row
matB <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)

In [4]:
matB

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [5]:
#by default it fills by column
matC <- matrix(1:9, nrow = 3, ncol = 3)

In [6]:
matC

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [7]:
vec1 <- 1:3
vec2 <- 3:1

In [8]:
#binding 2 vectors as 2 different rows
rbind(vec1,vec2)

[,1] [,2] [,3]
vec1 1    2    3   
vec2 3    2    1

In [9]:
#binding 2 vectors as 2 different cols
cbind(vec1, vec2)

vec1 vec2
[1,] 1    3   
[2,] 2    2   
[3,] 3    1

In [12]:
#create matrix using array function by specifying two dimension
mat <- array(1:9, dim = c(3,3))

In [11]:
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [13]:
#Check if some data structure is matrix or not
is.matrix(mat)

[1] TRUE

In [14]:
#nrow - function returning number of rows
nrow(matA)

[1] 2

In [15]:
#ncol - function returning number of cols
ncol(matA)

[1] 4

In [16]:
matA[2,]

[1] 1 1 1 1

In [18]:
#Contents of second row
mat[2,]

[1] 2 5 8

### Matrix operations
* You cannot do operations of matrix if they are not of same size

In [19]:
matADD <- matB + matA

ERROR: Error in matB + matA: non-conformable arrays


In [22]:
matC

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [21]:
matB

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [25]:
## Matrix add
matB + matC

[,1] [,2] [,3]
[1,]  2    6   10  
[2,]  6   10   14  
[3,] 10   14   18

In [26]:
### Matrix multiplication
matA

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 1    1    1    1

In [31]:
matB %*% matB

[,1] [,2] [,3]
[1,]  30   36   42 
[2,]  66   81   96 
[3,] 102  126  150

In [32]:
matB

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [33]:
matB * matB

[,1] [,2] [,3]
[1,]  1    4    9  
[2,] 16   25   36  
[3,] 49   64   81

In [35]:
rownames(matB) <- c("r1", "r2", "r3")

In [36]:
matB

[,1] [,2] [,3]
r1 1    2    3   
r2 4    5    6   
r3 7    8    9

In [37]:
colnames(matB) <- c("c1","c2","c3")

In [38]:
matB

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

### Creating a data frame and accessing its properties

In [48]:
a <- data.frame(ID=1:5, spent=c(5,4,3,2,1))

In [49]:
a

ID spent
1 1  5    
2 2  4    
3 3  3    
4 4  2    
5 5  1

In [46]:
data.frame(ID = 1:5, hourSpetOnInternet = c(5,3,4,1,2))

ID hourSpetOnInternet
1 1  5                 
2 2  3                 
3 3  4                 
4 4  1                 
5 5  2

In [51]:
str(a)

'data.frame':	5 obs. of  2 variables:
 $ ID   : int  1 2 3 4 5
 $ spent: num  5 4 3 2 1


In [53]:
a[1,]

ID spent
1 1  5

In [54]:
#A factor is another R data type, this is being used to represent 
#categorical variables such as, 1 for M and 2 for F category.

datB <- data.frame(ID = 1:5, hourSpetOnInternet = c(5,3,4,1,2),  
    GENDER = c("M", "F", "F", "M", "F"), stringsAsFactors=FALSE)

In [55]:
datB

ID hourSpetOnInternet GENDER
1 1  5                  M     
2 2  3                  F     
3 3  4                  F     
4 4  1                  M     
5 5  2                  F

In [56]:
datC <- data.frame(ID = 1:5, hourSpetOnInternet = c(5,3,4,1,2),  
    GENDER = c("M", "F", "F", "M", "F"))

In [60]:
datC

ID hourSpetOnInternet GENDER
1 1  5                  M     
2 2  3                  F     
3 3  4                  F     
4 4  1                  M     
5 5  2                  F

### Creating an array and accessing its properties

In [61]:
#Creats a 3D array of dim 2,2,4
arrayA <- array(1:16, dim=c(2,2,4))

In [63]:
arrayA

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

, , 4

     [,1] [,2]
[1,]   13   15
[2,]   14   16

In [65]:
#Second matrix of arrayA
arrayA[,,2]

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [66]:
arrayA[1,1,2]

[1] 5

In [70]:
arrayA[1,1,2]

[1] 5

In [71]:
column.names <- c("COL1","COL2")
row.names <- c("ROW1","ROW2")
matrix.names <- c("m1","m2", "m3", "m4")

In [72]:
arrayB <- array(1:16, dim=c(2,2,4), dimnames =list(row.names,     
    column.names, matrix.names))

In [74]:
cat(arrayB)

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16

### Creating a list from a combination of vector, matrix, and data frames
* A list is the natural generalization of a data frame in R. 
* A data frame is a rectangular arrangement of rows and columns where each of the column must be of same length. 
* A list can contain variety of heterogeneous objects with various lengths and data types. 
* An array contains only one data type whereas, a list could contain heterogeneous data types of various lengths.

In [75]:
cVec <- c("Cricket", "Football", "Basketball", "Rugby")
nVec <- c(1:10)
Lvec <- c(TRUE, FALSE, FALSE, TRUE)
matA <- matrix(1, nrow=2, ncol=2)
datA <- data.frame(ID = 1:5, hourSpetOnInternet = c(5,3,4,1,2),  
GENDER = c("M", "F", "F", "M", "F"))
arrayA <- array(1:16, dim=c(2,2,4))

In [76]:
listA <- list(cVec, nVec, Lvec, matA, datA, arrayA)

In [77]:
listA

[[1]]
[1] "Cricket"    "Football"   "Basketball" "Rugby"     

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[3]]
[1]  TRUE FALSE FALSE  TRUE

[[4]]
     [,1] [,2]
[1,]    1    1
[2,]    1    1

[[5]]
  ID hourSpetOnInternet GENDER
1  1                  5      M
2  2                  3      F
3  3                  4      F
4  4                  1      M
5  5                  2      F

[[6]]
, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

, , 4

     [,1] [,2]
[1,]   13   15
[2,]   14   16

In [78]:
listB <- list(vector1 = cVec, vector2 = nVec, vector3 = Lvec, matrix1 = matA, data1 = datA, array1 = arrayA)

In [79]:
listB

$vector1
[1] "Cricket"    "Football"   "Basketball" "Rugby"     

$vector2
 [1]  1  2  3  4  5  6  7  8  9 10

$vector3
[1]  TRUE FALSE FALSE  TRUE

$matrix1
     [,1] [,2]
[1,]    1    1
[2,]    1    1

$data1
  ID hourSpetOnInternet GENDER
1  1                  5      M
2  2                  3      F
3  3                  4      F
4  4                  1      M
5  5                  2      F

$array1
, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

, , 4

     [,1] [,2]
[1,]   13   15
[2,]   14   16

In [81]:
str(listA)

List of 6
 $ : chr [1:4] "Cricket" "Football" "Basketball" "Rugby"
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : logi [1:4] TRUE FALSE FALSE TRUE
 $ : num [1:2, 1:2] 1 1 1 1
 $ :'data.frame':	5 obs. of  3 variables:
  ..$ ID                : int [1:5] 1 2 3 4 5
  ..$ hourSpetOnInternet: num [1:5] 5 3 4 1 2
  ..$ GENDER            : Factor w/ 2 levels "F","M": 2 1 1 2 1
 $ : int [1:2, 1:2, 1:4] 1 2 3 4 5 6 7 8 9 10 ...


In [84]:
listA[[1]]

[1] "Cricket"    "Football"   "Basketball" "Rugby"

In [85]:
listB$data1

ID hourSpetOnInternet GENDER
1 1  5                  M     
2 2  3                  F     
3 3  4                  F     
4 4  1                  M     
5 5  2                  F

### Converting matrix to data frame and data frame to matrix
* The conversion from a matrix to a data frame works simply by assigning column names and then assign the class property as data.frame. Since a matrix only contain one data type, the resultant data frame also contain only one data type.
* The conversion of data frame to matrix with heterogeneous data types, works little bit differently. Firstly, it converts all columns into higher and more general data types

In [86]:
M1 <- matrix(1:9, nrow=3, ncol= 3, byrow=TRUE)
D1 <- data.frame(x1= c(1,3,2,4,5), x2= c("Cricket", "Football",  
    "Basketball", "Rugby", "Baseball" ))

In [87]:
M1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [88]:
D1

x1 x2        
1 1  Cricket   
2 3  Football  
3 2  Basketball
4 4  Rugby     
5 5  Baseball

In [89]:
M1toDF <- as.data.frame(M1)

In [90]:
M1toDF

V1 V2 V3
1 1  2  3 
2 4  5  6 
3 7  8  9

In [91]:
as.matrix(D1)

x1 x2        
[1,] 1  Cricket   
[2,] 3  Football  
[3,] 2  Basketball
[4,] 4  Rugby     
[5,] 5  Baseball