In [1]:
sample(1:6, size = 5)

[1] 5 2 4 1 6

In [3]:
sample(letters, size = 3)

[1] "e" "c" "t"

In [5]:
sample(list(a = 1, b = c(2, 3), c = c(3, 4, 5)), size = 2)

$b
[1] 2 3

$a
[1] 1

In [6]:
len <- c(3,4,5)

In [7]:
x <- list()

In [8]:
for(i in 1:3){
    x[[i]] <- rnorm(len[i])
}

In [9]:
x

[[1]]
[1]  0.8960081 -0.7418929 -0.5736326

[[2]]
[1]  1.5363023  0.9516732 -1.1089168 -0.4048071

[[3]]
[1]  0.007689926  0.473850513  0.490164044  0.414820164 -1.432077019

In [11]:
d = lapply(len,rnorm)

In [12]:
d

[[1]]
[1] 0.7703167 0.7418919 0.6861353

[[2]]
[1] -0.4247133 -1.3341822  0.2351321 -1.4698265

[[3]]
[1] -0.19982954 -1.48587268  0.07462221  0.33362982 -0.42439580

In [13]:
sapply(1:10, function (i) i ^ 2)

[1]   1   4   9  16  25  36  49  64  81 100

In [29]:
x1 <- list(c(1,2), c(2,3,5), c(1,3,3))

In [30]:
x1

[[1]]
[1] 1 2

[[2]]
[1] 2 3 5

[[3]]
[1] 1 3 3

In [31]:
sapply(x1, function(x) x ^ 2)

[[1]]
[1] 1 4

[[2]]
[1]  4  9 25

[[3]]
[1] 1 9 9

In [38]:
vapply(x, function(x) x ^ 2, numeric(2))

[,1] [,2] [,3]
[1,] 1    4    1   
[2,] 4    9    9

In [37]:
x

[[1]]
[1] 1 2

[[2]]
[1] 2 3

[[3]]
[1] 1 3

In [39]:
mat <- matrix(c(1,2,3,4), nrow = 2)

In [40]:
mat

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [41]:
apply(mat, 2 , sum)

[1] 3 7

In [42]:
mat2 <- matrix(1:16, nrow = 4)

In [43]:
mat2

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [44]:
apply(mat2, 2, function(col) c(min = min(col), max = max(col)))

[,1] [,2] [,3] [,4]
min 1    5     9   13  
max 4    8    12   16